[tox]
env_list = py312
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    hypothesis
    ruff
    pyright
commands =
    pytest --cov=spite --cov-report=term-missing tests/
    ruff check .
    pyright
