[tox]
env_list = py315
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    pytest-asyncio
    hypothesis
    ruff
    pyright
commands =
    pytest tests/
    ruff check --fix .
    ruff format .
    pyright
